export type StoreAgent = {
  id: string;
  name: string;
  category: "Marketplace" | "Industry" | "Outreach" | "Ops" | "Finance";
  emoji: string;
  tagline: string;
  description: string;
  publisher: string;
  publisherVerified: boolean;
  installs: number;
  rating: number;
  reviewCount: number;
  monthly: number; // 0 = Free / Included
  setupFee?: number;
  revShare?: number; // platform's cut
  installed: boolean;
  featured?: boolean;
  capabilities: string[];
  integrations: string[];
};

export const STORE_AGENTS: StoreAgent[] = [
  {
    id: "as1",
    name: "Amazon Seller Agent",
    category: "Marketplace",
    emoji: "📦",
    tagline: "Find FBA winners, automate listings, win the buy box",
    description:
      "Scans Amazon BSR + Helium 10 + Jungle Scout signals to surface high-margin FBA opportunities. Auto-generates listings, A/B tests titles, and bids on the buy box.",
    publisher: "AVYN Labs",
    publisherVerified: true,
    installs: 18_412,
    rating: 4.8,
    reviewCount: 412,
    monthly: 99,
    setupFee: 0,
    revShare: 0.25,
    installed: true,
    featured: true,
    capabilities: [
      "BSR + keyword tracker",
      "Auto-listing generator",
      "Buy box monitor",
      "Review sentiment alerts",
    ],
    integrations: ["Amazon Seller Central", "Helium 10", "Keepa"],
  },
  {
    id: "as2",
    name: "TikTok Shop Agent",
    category: "Marketplace",
    emoji: "🎵",
    tagline: "Catch viral products before they peak on TikTok Shop",
    description:
      "Real-time TikTok Shop trend detection + creator outreach. Auto-launches affiliate seeding campaigns and tracks GMV per creator.",
    publisher: "AVYN Labs",
    publisherVerified: true,
    installs: 9_822,
    rating: 4.7,
    reviewCount: 218,
    monthly: 149,
    revShare: 0.25,
    installed: false,
    featured: true,
    capabilities: [
      "Live GMV tracker",
      "Creator-fit scoring",
      "Affiliate outreach automation",
      "Drop alerts",
    ],
    integrations: ["TikTok Shop", "TikTok Creator Marketplace"],
  },
  {
    id: "as3",
    name: "Shopify Store Builder",
    category: "Marketplace",
    emoji: "🛍️",
    tagline: "Spin up niche Shopify stores in 60 seconds",
    description:
      "Picks a winning product, spins up a themed Shopify store, writes descriptions + ad copy, and launches a starter ad set. Revenue share with platform.",
    publisher: "AVYN Labs",
    publisherVerified: true,
    installs: 4_201,
    rating: 4.5,
    reviewCount: 96,
    monthly: 199,
    setupFee: 99,
    revShare: 0.3,
    installed: false,
    capabilities: [
      "Theme + content generator",
      "Product import",
      "Ad-copy writer",
      "First-week ad launcher",
    ],
    integrations: ["Shopify", "Stripe", "Meta Ads", "Klaviyo"],
  },
  {
    id: "as4",
    name: "Real Estate Wholesaler",
    category: "Industry",
    emoji: "🏠",
    tagline: "Source distressed properties + outreach to buyers",
    description:
      "Pulls Redfin/Zillow + foreclosure feeds, matches to local cash buyers, and runs SMS outreach. Splits commission with the platform.",
    publisher: "Brick House AI",
    publisherVerified: false,
    installs: 1_142,
    rating: 4.3,
    reviewCount: 41,
    monthly: 299,
    revShare: 0.3,
    installed: false,
    capabilities: [
      "Distressed-property scanner",
      "Cash-buyer database",
      "SMS sequencer",
      "Title pre-check",
    ],
    integrations: ["Zillow", "Redfin", "Twilio", "DocuSign"],
  },
  {
    id: "as5",
    name: "Auto Parts Sourcing Agent",
    category: "Industry",
    emoji: "🔧",
    tagline: "Source OEM + aftermarket parts at wholesale",
    description:
      "Cross-references VIN + part numbers against 200+ wholesalers and dropshippers. Best for shops + auto e-commerce stores.",
    publisher: "TorqueAI",
    publisherVerified: true,
    installs: 622,
    rating: 4.6,
    reviewCount: 28,
    monthly: 199,
    revShare: 0.25,
    installed: false,
    capabilities: [
      "VIN → parts mapper",
      "Live wholesale pricing",
      "Cross-reference search",
      "Local shop quote-fan-out",
    ],
    integrations: ["RockAuto", "Parts Authority", "WHI Solutions"],
  },
  {
    id: "as6",
    name: "Beauty Brand Buyer Finder",
    category: "Industry",
    emoji: "💄",
    tagline: "Find indie beauty boutiques + Sephora-tier buyers",
    description:
      "Specialized buyer agent trained on beauty distribution. Identifies independent beauty buyers, indie boutiques, and chain category managers.",
    publisher: "GlowGraph",
    publisherVerified: true,
    installs: 824,
    rating: 4.7,
    reviewCount: 36,
    monthly: 149,
    revShare: 0.2,
    installed: false,
    capabilities: [
      "Buyer-by-aisle index",
      "Trade show ingest",
      "Indie boutique enrichment",
      "Sephora/Ulta category-manager finder",
    ],
    integrations: ["Faire", "Bulletin", "Pop Up Shop"],
  },
  {
    id: "as7",
    name: "Cold Email Warmup Agent",
    category: "Outreach",
    emoji: "📨",
    tagline: "Keep your sender domain healthy 24/7",
    description:
      "Auto-warms new domains, monitors blacklists, and rotates sender reputation across pools. Pairs with the core Outreach Agent.",
    publisher: "AVYN Labs",
    publisherVerified: true,
    installs: 12_103,
    rating: 4.9,
    reviewCount: 514,
    monthly: 49,
    installed: true,
    capabilities: ["Domain warmup", "Blacklist monitor", "Pool rotation", "DMARC/SPF check"],
    integrations: ["Postmark", "SendGrid", "Mailgun"],
  },
  {
    id: "as8",
    name: "Negotiation Specialist (B2B)",
    category: "Outreach",
    emoji: "🤝",
    tagline: "Trained on 10K+ wholesale negotiations",
    description:
      "Handles back-and-forth on volume discounts, payment terms, MOQ, and shipping. Drafts replies with human-in-the-loop approval.",
    publisher: "DealCraft AI",
    publisherVerified: true,
    installs: 2_881,
    rating: 4.6,
    reviewCount: 64,
    monthly: 249,
    revShare: 0.2,
    installed: false,
    featured: true,
    capabilities: [
      "Volume-discount calculator",
      "Net-terms playbook",
      "Counter-offer generator",
      "Approval queue",
    ],
    integrations: ["Gmail", "Outlook", "Slack approvals"],
  },
  {
    id: "as9",
    name: "Procurement Agent (Fortune 1000)",
    category: "Industry",
    emoji: "🏢",
    tagline: "Enterprise sourcing on autopilot",
    description:
      "Built for corporate procurement teams. Generates RFPs, scores suppliers, runs reverse auctions, and produces audit-ready savings reports.",
    publisher: "AVYN Enterprise",
    publisherVerified: true,
    installs: 142,
    rating: 4.9,
    reviewCount: 18,
    monthly: 2999,
    setupFee: 5000,
    installed: false,
    capabilities: [
      "RFP generator",
      "Reverse-auction runner",
      "SOX-ready audit log",
      "Supplier savings report",
    ],
    integrations: ["SAP Ariba", "Coupa", "Workday"],
  },
  {
    id: "as10",
    name: "Ad Media Buyer",
    category: "Outreach",
    emoji: "📈",
    tagline: "AI launches + scales TikTok / Meta / Google ads",
    description:
      "Auto-launches starter ad sets for top products, kills underperformers, and scales winners. Charges 10% of ad spend + $99/mo.",
    publisher: "AVYN Labs",
    publisherVerified: true,
    installs: 3_402,
    rating: 4.4,
    reviewCount: 87,
    monthly: 99,
    revShare: 0.1,
    installed: false,
    capabilities: [
      "TikTok ads launcher",
      "Meta CAPI",
      "Google Performance Max",
      "Auto-kill rules",
    ],
    integrations: ["Meta Ads", "TikTok Ads", "Google Ads"],
  },
  {
    id: "as11",
    name: "Invoice Collector",
    category: "Finance",
    emoji: "💰",
    tagline: "Chase unpaid wholesale invoices automatically",
    description:
      "Sends polite + escalating reminders, then routes to a human or collections after 60 days. Reduced A/R days by 38% on average.",
    publisher: "Ledger AI",
    publisherVerified: true,
    installs: 1_892,
    rating: 4.7,
    reviewCount: 48,
    monthly: 79,
    installed: false,
    capabilities: ["Reminder cadences", "Auto-statement generation", "DSO dashboard"],
    integrations: ["QuickBooks", "Xero", "Stripe", "Plaid"],
  },
  {
    id: "as12",
    name: "Margin Watchdog",
    category: "Finance",
    emoji: "🛡️",
    tagline: "Flags any deal selling below your margin floor",
    description:
      "Monitors every quote in real time. Blocks publishing if gross margin dips below the floor you set per category.",
    publisher: "AVYN Labs",
    publisherVerified: true,
    installs: 5_021,
    rating: 4.8,
    reviewCount: 142,
    monthly: 0,
    installed: true,
    capabilities: ["Per-category margin floor", "Real-time block", "Slack alerts"],
    integrations: ["Slack", "Email"],
  },
];

export const CATEGORIES = ["All", "Marketplace", "Industry", "Outreach", "Ops", "Finance"] as const;
