import type { Buyer } from "@/lib/buyers";
import type { Product } from "@/lib/products";
import type { ScrapeResult } from "@/lib/scrapers";
import type { Supplier } from "@/lib/suppliers";
import { BlobsBackend } from "@/lib/store-backends/blobs";
import { FileBackend } from "@/lib/store-backends/file";
import { KvBackend } from "@/lib/store-backends/kv";
import type { StoreBackend } from "@/lib/store-backends/types";

// ─── Storage keys ──────────────────────────────────────────────────────────
// Backend-agnostic — the file backend resolves these under DATA_DIR;
// the KV backend uses them as Redis key names directly.

const PRODUCTS_FILE = "products.json";
const RUNS_FILE = "agent-runs.json";
const SIGNALS_FILE = "signals.json";
const BUYERS_FILE = "discovered-buyers.json";
const DRAFTS_FILE = "drafts.json";
const SUPPLIERS_FILE = "discovered-suppliers.json";
const CRON_RUNS_FILE = "cron-runs.json";
const RISK_FLAGS_FILE = "risk-flags.json";
const PIPELINE_RUNS_FILE = "pipeline-runs.json";
const QUOTES_FILE = "quotes.json";
const SPEND_LEDGER_FILE = "spend-ledger.json";
const TRANSACTIONS_FILE = "transactions.json";
const REVENUE_LEDGER_FILE = "revenue-ledger.json";
const LEADS_FILE = "leads.json";
const INVITES_FILE = "invites.json";
const API_KEYS_FILE = "api-keys.json";
const BUSINESSES_FILE = "businesses.json";
const SUPPLY_EDGES_FILE = "supply-edges.json";

// ─── Backend selection ─────────────────────────────────────────────────────
// STORE_BACKEND=blobs → Netlify Blobs (recommended for Netlify deploys)
// STORE_BACKEND=kv    → Vercel KV / Upstash Redis
// STORE_BACKEND=file (default) → JSON files in ./data or /tmp on Vercel/Netlify
//   ⚠️ /tmp is ephemeral on serverless — do NOT use file in production.
//
// Once chosen, the backend is a singleton for the lifetime of the lambda.
// Switching at runtime is not supported — restart with new env vars.

let _backend: StoreBackend | null = null;
export function getBackend(): StoreBackend {
  if (_backend) return _backend;
  const choice = (process.env.STORE_BACKEND ?? "file").toLowerCase();
  if (choice === "blobs" || choice === "netlify-blobs") {
    _backend = new BlobsBackend();
  } else if (choice === "kv" || choice === "vercel-kv" || choice === "upstash") {
    _backend = new KvBackend();
  } else {
    _backend = new FileBackend();
  }
  return _backend;
}

/**
 * Override the backend (testing only). Pass null to revert to env-driven choice.
 */
export function __setBackendForTesting(b: StoreBackend | null) {
  _backend = b;
}

const all_keys = [
  PRODUCTS_FILE, RUNS_FILE, SIGNALS_FILE, BUYERS_FILE, DRAFTS_FILE,
  SUPPLIERS_FILE, CRON_RUNS_FILE, RISK_FLAGS_FILE, PIPELINE_RUNS_FILE,
  QUOTES_FILE, SPEND_LEDGER_FILE, TRANSACTIONS_FILE, REVENUE_LEDGER_FILE,
  LEADS_FILE,
];

/**
 * Best-effort warmup. Useful at lambda boot for KV backends so cold-start reads
 * are populated. Safe to call repeatedly and from any path.
 */
export async function warmupStore(): Promise<void> {
  const b = getBackend();
  if (b.warmup) await b.warmup(all_keys);
}

export type DiscoveredProduct = Product & {
  source: "agent";
  agent: string;
  discoveredAt: string; // ISO
  runId: string;
  rationale: string;
};

export type AgentRun = {
  id: string;
  agent: "trend-hunter" | "buyer-discovery" | "supplier-finder" | "outreach" | "negotiation" | "risk";
  startedAt: string;
  finishedAt: string;
  durationMs: number;
  status: "success" | "error";
  inputCategory: string | null;
  inputProductName?: string;
  productCount: number;
  buyerCount?: number;
  supplierCount?: number;
  modelUsed: string;
  inputTokens?: number;
  outputTokens?: number;
  estCostUsd?: number;
  usedFallback: boolean;
  errorMessage?: string;
  signalsUsed?: number;
  signalSources?: string[];
};

export type DiscoveredBuyer = Buyer & {
  source: "agent";
  agent: string;
  discoveredAt: string;
  runId: string;
  rationale: string;
  forProduct: string; // product name this buyer was discovered for
};

export type DiscoveredSupplier = Supplier & {
  source: "agent";
  agent: string;
  discoveredAt: string;
  runId: string;
  rationale: string;
  forProduct: string;
};

/**
 * Quote (slice 37) — formal pricing artifact tied to a draft.
 * Generated by the Quote Agent when the operator clicks "Build quote" on a
 * draft (typically after negotiation has surfaced a workable price/terms).
 *
 * Quotes have their own share-able URL via /api/quotes/[id]?t=<token>.
 */
export type Quote = {
  id: string;
  createdAt: string;
  draftId: string;       // parent draft
  pipelineId?: string;   // for cross-linking the run
  buyerCompany: string;
  buyerName: string;
  productName: string;
  // Line items
  unitPrice: number;
  quantity: number;
  subtotal: number;
  discountPct: number;
  discountAmount: number;
  total: number;
  currency: string;       // "USD"
  // Terms
  paymentTerms: string;   // "Net 30", "Net 45", "50% upfront, 50% on delivery"
  leadTimeDays: number;
  validForDays: number;   // days the quote is valid from createdAt
  shippingTerms: string;  // "FOB Origin", "DDP", etc.
  notes?: string;
  // Lifecycle
  status: "draft" | "sent" | "accepted" | "rejected" | "expired";
  acceptedAt?: string;
  rejectedAt?: string;
  // Tracked share link for the quote view
  shareToken: string;
  shareExpiresAt: string;
  // Audit
  modelUsed: string;
  estCostUsd?: number;
  usedFallback: boolean;
  generatedRationale?: string;  // AI's reasoning for the price/terms
};

// ─── Transactions: full deal-to-cash orchestration (slice 39) ───────────────
//
// A Transaction is the full lifecycle of a closed deal:
//
//   draft (operator created) →
//   proposed (sent to buyer) →
//   signed (buyer accepted contract) →
//   payment_pending (waiting for buyer's funds) →
//   escrow_held (platform holding payment) →
//   shipped (supplier dispatched) →
//   delivered (carrier confirmed delivery) →
//   released (escrow → supplier payout, platform takes fees) →
//   completed
//
// Side branches:
//   disputed (buyer raised an issue — funds frozen until resolution)
//   refunded (buyer got money back, supplier got nothing)
//   cancelled (operator killed it before payment)
//
// Money flow (Stripe Connect model):
//   buyer pays → platform Stripe account (escrow held)
//   on release: supplier gets payout, platform keeps fees
//   refund: buyer's card is credited back, no supplier payout
export type TransactionState =
  | "draft"
  | "proposed"
  | "signed"
  | "payment_pending"
  | "escrow_held"
  | "shipped"
  | "delivered"
  | "released"
  | "completed"
  | "disputed"
  | "refunded"
  | "cancelled";

export type TransactionEvent = {
  ts: string;
  state: TransactionState;
  actor: "operator" | "buyer" | "supplier" | "system" | "agent";
  detail: string;
  meta?: Record<string, unknown>;
};

export type Transaction = {
  id: string;
  quoteId: string;          // the parent quote that became this txn
  draftId: string;          // the outreach draft that generated the quote
  pipelineId?: string;      // upstream pipeline run (for analytics)
  buyerCompany: string;
  buyerName: string;
  buyerEmail?: string;      // resolved at proposal-send time
  productName: string;

  // Money — all USD cents to avoid float drift, displayed as dollars in UI
  unitPriceCents: number;
  quantity: number;
  subtotalCents: number;
  discountPctBps: number;   // basis points (1% = 100 bps) for precision
  discountCents: number;
  shippingCents: number;
  productTotalCents: number;  // subtotal − discount + shipping (what buyer pays)

  // Platform economics
  platformFeePctBps: number;  // default 800 bps = 8%
  platformFeeCents: number;   // computed at proposal time
  escrowFeePctBps: number;    // default 100 bps = 1% (Stripe Connect ~2.9% + 30¢ on top)
  escrowFeeCents: number;
  supplierPayoutCents: number; // productTotalCents − platformFee − escrowFee

  // Terms
  paymentTerms: string;      // "Net 30", "50% upfront", etc. (from quote)
  shippingTerms: string;     // "FOB Origin", "DDP"
  leadTimeDays: number;
  refundPolicy?: string;     // free-text: "30 days from delivery, unopened"

  // State + lifecycle
  state: TransactionState;
  stateHistory: TransactionEvent[];
  createdAt: string;
  updatedAt: string;

  // Contract
  contractToken?: string;    // public link for buyer to sign
  contractSignedAt?: string;
  contractSignerName?: string;
  contractSignerIp?: string;
  contractDocUrl?: string;   // DocuSign envelope URL when configured

  // Payment
  paymentProvider?: "stripe" | "simulated";
  stripePaymentIntentId?: string;
  stripeCheckoutSessionId?: string;
  stripeChargeId?: string;
  paymentReceivedAt?: string;
  paymentMethodLast4?: string;

  // Escrow
  escrowStartedAt?: string;
  escrowReleasedAt?: string;
  escrowReleaseAuthorizedBy?: "auto" | "operator" | "delivery_confirmed";

  // Shipping
  shippingProvider?: "shippo" | "manual" | "fedex" | "ups" | "dhl";
  trackingNumber?: string;
  carrierName?: string;
  shippedAt?: string;
  deliveredAt?: string;
  deliveryConfirmedBy?: "carrier" | "buyer_confirmed" | "operator";

  // Supplier payout
  supplierName?: string;
  supplierStripeAccountId?: string;  // Connect account
  supplierPayoutId?: string;
  supplierPayoutAt?: string;

  // Dispute / refund
  disputedAt?: string;
  disputeReason?: string;
  disputeResolution?: "refund_buyer" | "release_supplier" | "split" | "pending";
  /**
   * Operator's free-text rationale captured at resolve time. Persisted alongside
   * the resolution choice so audit trail shows WHY, not just WHAT. Max 500 chars
   * (enforced server-side); empty/null when the operator skipped the field.
   */
  disputeResolutionNotes?: string;
  refundedAt?: string;
  refundCents?: number;

  /**
   * Free-form operator scratchpad — anything not state-machine driven.
   * Examples: "Sarah said she'd ship by Friday", "Buyer was 3 days late
   * on last deal", "Watch this one — first order over $50K". Max 1000
   * chars (enforced server-side). Private to operators (not exposed via
   * the public buyer-page API).
   */
  operatorNotes?: string;
  operatorNotesUpdatedAt?: string;

  // AI confidence + risk
  aiConfidenceScore?: number;  // 0-100, computed at proposal time
  riskFlags?: string[];        // ids of any risk flags triggered

  // Public share token (buyer accesses /transaction/[id]?t=<token>)
  shareToken: string;
  shareExpiresAt: string;
};

// Revenue ledger entry — one per state transition that moves money
export type RevenueEntry = {
  id: string;
  transactionId: string;
  ts: string;
  kind: "platform_fee" | "escrow_fee" | "supplier_payout" | "refund" | "dispute_hold";
  cents: number;            // positive = inflow to platform, negative = outflow
  detail: string;
};

export type RiskFlag = {
  id: string;
  source: "agent" | "static";
  agent?: string;
  runId?: string;
  createdAt: string;
  severity: "Critical" | "High" | "Medium" | "Low";
  category: "Supplier Fraud" | "Buyer Fraud" | "Trademark" | "Restricted Product" | "Payment" | "Compliance";
  title: string;
  detail: string;
  recommended: string;
  subjectType: "supplier" | "buyer" | "product" | "general";
  subjectId?: string;
  subjectName?: string;
};

/**
 * Persisted pipeline-run snapshot. Used by the public /share/[id] view.
 * Token is required to access the share URL — IDs alone won't reveal data.
 */
export type ShareAccessEntry = {
  ts: string;          // ISO timestamp of the view
  ip?: string;         // best-effort, may be empty behind some proxies
  userAgent?: string;  // truncated to 200 chars
  referer?: string;    // where the click came from (null if direct)
  linkToken?: string;  // which named link was used (omitted = legacy/default token)
  linkLabel?: string;  // captured at view time so a later relabel doesn't rewrite history
};

/**
 * Public-viewer scope for a share link.
 *
 * - "full":      sees the entire run including OTHER buyers + drafts.
 *                Legacy default (back-compat) for the unnamed shareToken.
 *                Use ONLY for internal sharing (you, your team).
 *
 * - "recipient": product trends + suppliers + risk are visible, but
 *                buyerSummaries and draftSummaries are STRIPPED at the API.
 *                Default for new named per-recipient links — safe to send
 *                to a prospect without leaking who else you're pitching.
 *
 * Undefined on a named link is treated as "recipient" (safe default).
 * Undefined on the legacy default link is treated as "full" (back-compat).
 */
export type ShareScope = "full" | "recipient";

/**
 * A named, per-recipient share link. Multiple links can co-exist on one run —
 * each gets its own token, label, expiry, scope, and revoke state.
 */
export type ShareLink = {
  token: string;          // 24-char hex, unguessable
  label: string;          // human-friendly name shown in the dashboard ("John @ Acme")
  createdAt: string;
  expiresAt?: string;     // ISO; if absent, never-expires
  scope?: ShareScope;     // undefined → "recipient" for safety
  revoked?: boolean;
  revokedAt?: string;
};

export type StoredPipelineRun = {
  id: string;
  shareToken: string;
  /**
   * ISO timestamp after which the share link should return 410 Gone.
   * Older runs without this field are treated as never-expiring (back-compat).
   */
  shareExpiresAt?: string;
  /**
   * If true, the share link returns 410 Gone immediately regardless of expiry.
   * Set by an explicit POST /api/share/[id]/revoke. Cannot be undone — sender must run a new pipeline.
   */
  revoked?: boolean;
  revokedAt?: string;
  /**
   * Append-only log of successful views, capped at 50 most recent.
   * Lets the sender see if/when the link was opened by the recipient.
   */
  accessLog?: ShareAccessEntry[];
  /**
   * Named, per-recipient share links. Each has its own token + expiry + revoke state.
   * The legacy shareToken (above) acts as the unnamed default link for backward compat.
   */
  shareLinks?: ShareLink[];
  triggeredBy: "manual" | "cron";
  startedAt: string;
  finishedAt: string;
  durationMs: number;
  totals: {
    products: number;
    buyers: number;
    suppliers: number;
    drafts: number;
    riskFlags: number;
    totalCost: number;
  };
  // Compact summaries — drop sensitive fields like buyer.email
  productSummaries: Array<{
    id: string;
    name: string;
    category: string;
    emoji: string;
    demandScore: number;
    rationale?: string;
  }>;
  buyerSummaries: Array<{
    id: string;
    company: string;
    type: string;
    location: string;
    fit: number;
    intentScore: number;
    forProduct: string;
    rationale?: string;
  }>;
  supplierSummaries: Array<{
    id: string;
    name: string;
    country: string;
    type: string;
    unitPrice: number;
    moq: number;
    leadTimeDays: number;
    riskScore: number;
    forProduct: string;
    rationale?: string;
  }>;
  draftSummaries: Array<{
    id: string;
    buyerCompany: string;
    buyerName: string;
    productName: string;
    emailSubject: string;
    emailPreview: string;
  }>;
  riskFlagSummaries: Array<{
    severity: string;
    category: string;
    title: string;
    detail: string;
  }>;
  steps: Array<{
    agent: string;
    status: "success" | "error";
    durationMs: number;
    detail: string;
  }>;

  /**
   * Lifecycle state for chunked / async pipeline execution.
   * - undefined or "completed": classic flow — runPipeline ran end-to-end
   * - "running": stages are landing in real time via /api/agents/pipeline/[id]/...
   * - "failed": a stage hit an unrecoverable error and the run was abandoned
   *
   * Old runs without this field are treated as "completed" for back-compat.
   */
  status?: "running" | "completed" | "failed";
  errorMessage?: string;
  /**
   * Original run options — needed by the chunked stage runners so the buyer
   * /outreach stages know how many to discover per product.
   */
  options?: {
    maxBuyersPerProduct?: number;
    findSuppliers?: boolean;
  };
};

export type CronRun = {
  id: string;
  ranAt: string;
  durationMs: number;
  status: "success" | "error";
  pipelineId: string;
  totals: {
    products: number;
    buyers: number;
    suppliers: number;
    drafts: number;
    totalCost: number;
  };
  errorMessage?: string;
};

export type LeadStatus = "new" | "contacted" | "qualified" | "won" | "lost";

export type Lead = {
  id: string;
  createdAt: string;        // ISO
  updatedAt: string;        // ISO
  // Step 0 — Business Details
  name: string;
  email: string;
  company: string;
  phone?: string;
  companySize?: string;     // e.g. "11–50"
  industry?: string;        // e.g. "Wholesale / B2B"
  // Step 1 — Requirements
  useCases: string[];       // ids from USE_CASES on /contact
  timeline?: string;        // e.g. "Within 1 month"
  budget?: string;
  // Step 2 — Solutions
  message?: string;
  // Operator-side
  source: "contact-form" | "signup-form";
  status: LeadStatus;
  notes?: string;           // internal operator notes
  // Light fingerprint for spam triage
  ipHash?: string;
  userAgent?: string;
  // ── AI auto-reply (slice: lead-followup) ─────────────────────────────────
  // Set when /api/leads asynchronously fires the Anthropic-generated welcome
  // email/SMS to the lead. `pending` = scheduled, `sent` = email left the
  // platform, `skipped` = no transport configured / consent missing,
  // `error` = handler threw. Operator sees this in the /leads detail panel.
  aiReply?: {
    status: "pending" | "sent" | "skipped" | "error";
    at: string;             // ISO when status was set
    subject?: string;       // generated email subject
    body?: string;          // generated email body (plain text)
    smsBody?: string;       // SMS body if Twilio path fired
    smsSentTo?: string;     // phone number SMS was actually sent to
    channel?: ("email" | "sms")[];
    model?: string;         // anthropic model id used
    estCostUsd?: number;
    errorMessage?: string;
  };
  // Auto-followup history. Each entry is one additional AI touch fired by the
  // /api/cron/lead-followups job after N days of buyer silence. The first
  // entry is the day-3 follow-up; subsequent are added if/when more cadences
  // ship. Operator-side "contacted" status manually marked by the operator
  // SUPPRESSES auto-followup to avoid stepping on a real conversation.
  aiFollowups?: Array<{
    at: string;
    daysSinceCreated: number;
    status: "sent" | "skipped" | "error";
    subject?: string;
    body?: string;
    model?: string;
    estCostUsd?: number;
    errorMessage?: string;
  }>;
  // Re-submission history. Whenever a known email submits the form again,
  // we merge into the existing Lead instead of creating a duplicate, and
  // append an entry here so the operator can see the audit trail.
  // - within 5 minutes  → silent dedupe (no entry, no AI re-trigger)
  // - longer            → entry with the changed fields and a fresh AI reply
  resubmissions?: Array<{
    at: string;
    source: "contact-form" | "signup-form";
    changedFields: string[];          // names of fields that received new values
    newMessage?: string;               // if a new message body was provided
    triggeredAiReply: boolean;
  }>;
  lastSubmittedAt?: string;             // ISO of most recent submission
  // ── Lead → Buyer promotion (slice: lead-promotion) ───────────────────────
  // Set when an operator (or auto-promote rule) one-clicks the lead into a
  // DiscoveredBuyer record on /leads. Once set, the same lead can't be
  // promoted again — UI shows "Promoted" instead of the button. The buyer
  // record itself lives in `discovered-buyers` and feeds the Outreach Agent.
  promotedToBuyerId?: string;           // DiscoveredBuyer.id
  promotedAt?: string;                  // ISO when promotion happened
  promotedBy?: "operator" | "auto";     // who fired the promotion
};

/**
 * Workspace invite — operator invites a teammate via email + role. Stored
 * in invites.json. Status starts as "pending"; flips to "cancelled" when
 * the operator revokes, "expired" when older than INVITE_EXPIRY_DAYS, and
 * "accepted" once the invitee onboards (acceptance flow ships in a
 * follow-up; for now invites are visible + cancellable but not yet
 * acceptable — operator can see who's been asked).
 *
 * SECURITY NOTE: this slice does NOT yet enforce roles in middleware.
 * Today's auth model is single ADMIN_TOKEN/cookie — every authenticated
 * caller has owner privileges. Roles are stored so the operator can plan
 * the team, and so the next slice (per-user identity + role enforcement)
 * has data to work with.
 */
export type InviteRole = "Admin" | "Operator" | "Viewer" | "Billing";
export type InviteStatus = "pending" | "accepted" | "cancelled" | "expired";

export type Invite = {
  id: string;                       // inv_<random>
  email: string;                    // recipient (lowercased on write)
  role: InviteRole;
  status: InviteStatus;
  createdAt: string;                // ISO
  expiresAt: string;                // ISO (createdAt + INVITE_EXPIRY_DAYS)
  invitedBy: string;                // operator name/email at create time
  acceptedAt?: string;              // ISO if accepted
  acceptedName?: string;            // display name the invitee provided on accept
  cancelledAt?: string;             // ISO if cancelled
  // Single-use token for the public acceptance flow at /invite/[token].
  // The token IS the auth — anyone with it can view + accept the invite,
  // so it's high-entropy (24 random bytes base64url) and the link is sent
  // only to the invited email address. NEVER include this token in any
  // operator-facing surface (admin UI, audit log, etc).
  token: string;
};

/**
 * Programmatic API key — bearer auth for /api/v1/* endpoints. Each key has
 * an explicit scope set; requests are denied unless the key carries the
 * scope the endpoint requires.
 *
 * Storage: we store ONLY the SHA-256 hash of the secret + a 12-char prefix
 * (e.g. "sk_live_4f29ab"). The raw secret is shown to the operator exactly
 * ONCE at creation time and is never recoverable — same model as Stripe /
 * GitHub. Lookup is by hash so even a database leak doesn't expose live
 * keys.
 */
export type ApiKeyScope =
  | "read:health"          // /api/v1/health — minimal, useful for monitoring
  | "read:insights"        // outreach insights aggregation
  | "read:leads"           // list captured leads
  | "read:campaigns"       // derived campaigns surface
  | "write:leads";         // future: programmatic POST /api/v1/leads

export type ApiKeyEnvironment = "Production" | "Test";
export type ApiKeyStatus = "Active" | "Revoked";

export type ApiKey = {
  id: string;                        // key_<random>
  name: string;                      // operator-supplied label
  prefix: string;                    // first 12 chars of the secret (e.g. "sk_live_4f29")
  hashedSecret: string;              // SHA-256 hex of the full secret
  scopes: ApiKeyScope[];
  environment: ApiKeyEnvironment;
  status: ApiKeyStatus;
  createdAt: string;                 // ISO
  createdBy: string;                 // operator email at creation time
  lastUsedAt?: string;               // ISO
  revokedAt?: string;                // ISO if revoked
  // Rolling 24h usage — array of ISO timestamps for each request, trimmed
  // older-than-24h on each recordApiKeyUse() call. Reading uses .length.
  usageWindow: string[];
};

/**
 * Business Directory — the universe of businesses we know about, from any
 * source: operator CSV uploads, lead → buyer promotions, future Data Axle
 * pulls, future Census imports. Distinct from `DiscoveredBuyer` because:
 *   - DiscoveredBuyer is pipeline-derived (per-product, agent-imagined)
 *   - BusinessRecord is the canonical, deduped, queryable directory
 *
 * Geography is structured (state/zip/lat/lng) so we can query "all
 * roofers in Dallas zip 75201" without scanning. Industry uses both a
 * free-text label AND optional NAICS so we can map to standard codes.
 *
 * Suppression: status="do_not_contact" OR doNotContact=true OR optedOutAt
 * present → never include in outreach. Helpers below enforce this.
 */
export type BusinessStatus =
  | "active"           // never contacted; eligible for outreach
  | "queued"           // selected for upcoming outreach
  | "contacted"        // outreach sent, no reply yet
  | "responded"        // buyer replied (web or email)
  | "won"              // closed/onboarded
  | "lost"             // dead deal (operator marked)
  | "do_not_contact";  // operator-marked or auto-suppressed

export type BusinessSource =
  | "manual"           // operator added one-by-one
  | "csv_import"       // bulk imported via CSV
  | "lead_promote"     // promoted from /leads
  | "agent_discover"   // surfaced by buyer-discovery agent
  | "data_axle"        // future: Data Axle bulk
  | "google_places"    // future: Google Places adapter
  | "census";          // future: Census Business Patterns

export type BusinessRecord = {
  id: string;                       // biz_<random>
  // ── Identity ──────────────────────────────────────────────────────────
  name: string;                     // company / DBA name (required)
  legalName?: string;               // legal entity if different
  ein?: string;                     // tax ID (optional, often unknown)
  // ── Contact ───────────────────────────────────────────────────────────
  email?: string;                   // lowercased on write
  phone?: string;                   // E.164 preferred but free-text OK
  website?: string;                 // bare domain or full URL
  // ── Geographic — structured for query ─────────────────────────────────
  address1?: string;
  address2?: string;
  city?: string;
  county?: string;
  state?: string;                   // 2-letter US state code preferred
  zip?: string;                     // 5 or 9 digit
  country: string;                  // ISO-3166 alpha-2; defaults to "US"
  lat?: number;
  lng?: number;
  // ── Classification ────────────────────────────────────────────────────
  industry?: string;                // free-text: "Roofing", "Pet Supplies"
  naicsCode?: string;               // 2-6 digit NAICS
  sicCode?: string;                 // legacy SIC
  employeesBand?: string;           // "1-10" / "11-50" / "51-200" / etc.
  revenueBand?: string;             // "$0-1M" / "$1-5M" / etc.
  yearFounded?: number;
  // ── Decision-maker (when known) ───────────────────────────────────────
  contactName?: string;
  contactTitle?: string;
  // ── Status + lifecycle ────────────────────────────────────────────────
  status: BusinessStatus;
  source: BusinessSource;
  notes?: string;                   // operator-only free-text
  tags?: string[];                  // arbitrary segmentation labels
  createdAt: string;                // ISO
  updatedAt: string;                // ISO
  // ── Outreach tracking ─────────────────────────────────────────────────
  lastContactedAt?: string;         // ISO of last outreach send
  outreachCount?: number;           // total outreach attempts
  lastDraftId?: string;             // most recent OutreachDraft.id
  // ── Suppression ───────────────────────────────────────────────────────
  doNotContact?: boolean;           // explicit operator flag
  optedOutAt?: string;              // ISO when buyer opted out
  optedOutReason?: string;          // "unsubscribe-link" / "complaint" / etc.
  // ── AI Profile (slice 3 of Business Network Intelligence) ─────────────
  // Set by the Business Profile Agent (lib/agents/businessProfile.ts) when
  // it fetches the business's homepage and asks Claude to extract what
  // they sell, who their likely suppliers/distributors are, etc. Updated
  // on each /profile scan. Confidence is the model's own self-rating of
  // how solid each inference is (homepage-only data is fuzzy).
  //
  // This data feeds the Business Outreach Agent — when present, the
  // agent personalizes the pitch with concrete signals ("I see you
  // carry Brand X, we have a better supplier for that") instead of the
  // generic industry-level pitch.
  aiProfile?: {
    scannedAt: string;              // ISO when the scan ran
    homepageUrl?: string;           // URL that was actually fetched (after redirects)
    productsSold: string[];         // 0-10 short labels ("commercial roofing", "shingles")
    likelySupplierBrands: string[]; // 0-10 brand names visible in copy/logos
    likelyDistributors: string[];   // 0-5 channel partners they sell through
    industryRefined?: string;       // more specific than CSV import (e.g. "Commercial roofing contractor" vs "Roofing")
    summary?: string;               // 1-2 sentence operator-readable summary
    confidence: number;             // 0-100 self-rating of the inferences
    modelUsed: string;              // anthropic model id or "fallback"
    estCostUsd?: number;            // total Anthropic cost for this scan
    fetchError?: string;            // populated when homepage fetch fails
    usedFallback: boolean;          // true if Anthropic call skipped/failed
  };
};

/**
 * Returns true when a business should NEVER receive outreach. Caller MUST
 * check this before sending to any business — it's the suppression gate.
 */
export function isBusinessSuppressed(b: BusinessRecord): boolean {
  if (b.status === "do_not_contact") return true;
  if (b.doNotContact) return true;
  if (b.optedOutAt) return true;
  return false;
}

/**
 * SupplyEdge — the relationship layer of the Commercial Intelligence
 * Graph. One edge per (fromBusiness, toName, kind) triplet, deduped
 * on upsert. The graph powers:
 *
 *   - "Who currently supplies this business?" (query by fromId)
 *   - "Who buys from this brand?" (query by toName)
 *   - "Where is this product distributed?" (query by kind=distributes_through)
 *   - "Find better suppliers for businesses currently using X" (slice 5)
 *
 * Sources of edges:
 *   - `ai_profile`: extracted from a business's homepage during the
 *     Business Profile Agent scan. Confidence inherits from the scan's
 *     overall confidence.
 *   - `transaction`: observed when a real AVYN transaction releases or
 *     completes. Highest signal — confidence=100. Wired in slice 5.
 *   - `operator`: manually curated by the operator (future UI).
 *   - `partner`: imported from a partner feed (future).
 */
export type SupplyEdgeKind =
  | "sources_from"          // fromBusiness BUYS from toName (toName is their supplier)
  | "distributes_through"   // fromBusiness SELLS through toName (Amazon, retailers, etc.)
  | "competes_with"         // future: similar product mix
  | "partners_with";        // future: explicit partnership

export type SupplyEdgeSource = "ai_profile" | "transaction" | "operator" | "partner";

export type SupplyEdge = {
  id: string;                    // edge_<random>
  fromBusinessId: string;        // BusinessRecord.id (always a real business in our directory)
  fromBusinessName: string;      // denormalized for fast display
  toName: string;                // brand/company name (may or may not have an id)
  toBusinessId?: string;         // BusinessRecord.id if `toName` is also in the directory
  kind: SupplyEdgeKind;
  source: SupplyEdgeSource;
  confidence: number;            // 0-100; transaction-observed = 100; ai_profile inherits scan confidence
  evidence?: string;             // 1-line context ("homepage lists Brand X under 'partners'", "txn t_abc closed 2026-05-10")
  observedAt: string;            // ISO; when this edge was first learned
  lastSeenAt: string;            // ISO; updated on every re-observation (re-scan, repeat txn)
  // Outbound discovery — when AVYN later finds a different (cheaper, faster,
  // closer) supplier for the same product, we record that suggestion here.
  // Operator UI can show "we found 3 alternatives" without re-querying.
  alternativesFound?: number;
};

/**
 * Composite dedup key for upserts. Lowercased + trimmed so "Brand X"
 * and "brand x" don't double-write.
 */
function supplyEdgeDedupKey(e: Pick<SupplyEdge, "fromBusinessId" | "toName" | "kind">): string {
  return `${e.fromBusinessId}|${e.toName.trim().toLowerCase()}|${e.kind}`;
}

export type ThreadMessage = {
  id: string;
  role: "agent" | "buyer";
  subject?: string;
  body: string;
  at: string;
  runId?: string;        // for agent-generated counter-offers
  cost?: number;
  summary?: string;       // AI rationale (counter-offer)
  recommendedAction?: string;
};

export type OutreachDraft = {
  id: string;
  runId: string;
  /**
   * Pipeline run that produced this draft. Populated by pipeline.finalize().
   * Older drafts (pre-slice-28) won't have this — fall back gracefully at send time.
   */
  pipelineId?: string;
  createdAt: string;
  buyerId: string;
  buyerCompany: string;
  buyerName: string;
  buyerTitle: string;
  productName: string;
  status: "draft" | "approved" | "sent" | "rejected";
  email: { subject: string; body: string };
  linkedin: { body: string };
  sms: { body: string };
  modelUsed: string;
  estCostUsd?: number;
  usedFallback: boolean;
  thread?: ThreadMessage[]; // additional messages after the original draft
  sentAt?: string;
  sentToEmail?: string;
  redirectedFromEmail?: string;
  messageId?: string;
  emailProvider?: "postmark" | "resend" | "fallback";
  sendSimulated?: boolean;
  sendError?: string;
  /**
   * Body actually sent to the email provider — typically the Claude-generated
   * email.body PLUS an appended "View proposal: <url>" line. Kept separate from
   * email.body so the review UI keeps showing the original generated content.
   */
  sentBody?: string;
  /**
   * Token of the recipient-scoped share link auto-minted at send time. Pairs with
   * the draft's pipelineId — together they identify the link in the parent run's
   * shareLinks[] array. Null when send-time minting failed (no pipelineId on draft,
   * or store error).
   */
  shareLinkToken?: string;
  shareLinkUrl?: string;
  /**
   * Public web-reply token. Buyers receive a /reply/<replyToken> link in the
   * outreach email body — clicking it opens a branded reply page where they
   * can respond without touching email. Submissions append a ThreadMessage
   * with role: "buyer" to this draft's thread.
   *
   * The token IS the auth (high-entropy 24 random bytes base64url) and is
   * only sent to the buyer's resolved email address. NEVER include it in
   * any operator-facing surface — operator sees the resulting ThreadMessages,
   * not the token.
   */
  replyToken?: string;
  replyUrl?: string;
  /**
   * Per-channel send state (slice 36). The email-only fields above stay for
   * back-compat. Each channel gets its own tracked share link variant so opens
   * can be attributed to the channel that drove them.
   */
  smsSentAt?: string;
  smsSentTo?: string;
  smsSimulated?: boolean;
  smsMessageId?: string;
  smsShareLinkToken?: string;
  smsShareLinkUrl?: string;
  smsSentBody?: string;
  smsSendError?: string;
  linkedinSentAt?: string;
  linkedinSentTo?: string;
  linkedinSimulated?: boolean;
  linkedinShareLinkToken?: string;
  linkedinShareLinkUrl?: string;
  linkedinSentBody?: string;
  linkedinSendError?: string;
  /**
   * If this draft is a follow-up to a previous one, points back at it. Lets the
   * UI render the lineage and prevents the follow-up agent from generating
   * an infinite chain of re-pitches.
   */
  parentDraftId?: string;
  followupNumber?: number;  // 1 = first follow-up, 2 = second, etc.
  followupReason?: string;  // why this followup was generated ("no opens in 3d")
  // CRM stage override (slice 35). Without this, stage is derived from lifecycle:
  //   draft → Prospecting; sent → Contacted; buyer-replied → Negotiation; rejected → Closed Lost
  dealStage?:
    | "Prospecting"
    | "Contacted"
    | "Negotiation"
    | "Quotation"
    | "Closed Won"
    | "Closed Lost";
  dealValue?: number;       // estimated annual contract value, USD
  dealUnits?: number;       // estimated initial order size
};

// ─── Spend ledger (slice: production hardening) ────────────────────────────
// Tracks per-day Anthropic spend so the circuit breaker can refuse calls
// when the daily budget is exceeded. One entry per UTC date.
export type SpendLedgerEntry = {
  date: string;        // YYYY-MM-DD UTC
  callCount: number;
  totalCostUsd: number;
  byAgent: Record<string, { calls: number; cost: number }>;
};

// ─── Public store API — all async, backend-agnostic ───────────────────────

export const store = {
  // Products
  async getProducts(): Promise<DiscoveredProduct[]> {
    return getBackend().read<DiscoveredProduct[]>(PRODUCTS_FILE, []);
  },
  async saveProducts(items: DiscoveredProduct[]): Promise<void> {
    const existing = await store.getProducts();
    const all = [...items, ...existing].slice(0, 200);
    await getBackend().write(PRODUCTS_FILE, all);
  },

  // Agent runs
  async getRuns(): Promise<AgentRun[]> {
    return getBackend().read<AgentRun[]>(RUNS_FILE, []);
  },
  async saveRun(run: AgentRun): Promise<void> {
    const existing = await store.getRuns();
    const all = [run, ...existing].slice(0, 100);
    await getBackend().write(RUNS_FILE, all);
  },

  // Signals (singleton, latest scrape)
  async getSignals(): Promise<ScrapeResult | null> {
    return getBackend().read<ScrapeResult | null>(SIGNALS_FILE, null);
  },
  async saveSignals(result: ScrapeResult): Promise<void> {
    await getBackend().write(SIGNALS_FILE, result);
  },

  // Discovered buyers
  async getDiscoveredBuyers(): Promise<DiscoveredBuyer[]> {
    return getBackend().read<DiscoveredBuyer[]>(BUYERS_FILE, []);
  },
  async saveDiscoveredBuyers(items: DiscoveredBuyer[]): Promise<void> {
    const existing = await store.getDiscoveredBuyers();
    const all = [...items, ...existing].slice(0, 200);
    await getBackend().write(BUYERS_FILE, all);
  },

  // Discovered suppliers
  async getDiscoveredSuppliers(): Promise<DiscoveredSupplier[]> {
    return getBackend().read<DiscoveredSupplier[]>(SUPPLIERS_FILE, []);
  },
  async saveDiscoveredSuppliers(items: DiscoveredSupplier[]): Promise<void> {
    const existing = await store.getDiscoveredSuppliers();
    const all = [...items, ...existing].slice(0, 200);
    await getBackend().write(SUPPLIERS_FILE, all);
  },

  // Cron runs
  async getCronRuns(): Promise<CronRun[]> {
    return getBackend().read<CronRun[]>(CRON_RUNS_FILE, []);
  },
  async saveCronRun(run: CronRun): Promise<void> {
    const existing = await store.getCronRuns();
    const all = [run, ...existing].slice(0, 50);
    await getBackend().write(CRON_RUNS_FILE, all);
  },

  // Risk flags
  async getRiskFlags(): Promise<RiskFlag[]> {
    return getBackend().read<RiskFlag[]>(RISK_FLAGS_FILE, []);
  },
  async saveRiskFlags(flags: RiskFlag[]): Promise<void> {
    const existing = await store.getRiskFlags();
    const all = [...flags, ...existing].slice(0, 200);
    await getBackend().write(RISK_FLAGS_FILE, all);
  },

  // Inbound leads from /contact
  async getLeads(): Promise<Lead[]> {
    return getBackend().read<Lead[]>(LEADS_FILE, []);
  },
  async getLead(id: string): Promise<Lead | null> {
    const all = await store.getLeads();
    return all.find((l) => l.id === id) ?? null;
  },
  async getLeadByEmail(email: string): Promise<Lead | null> {
    const norm = email.trim().toLowerCase();
    if (!norm) return null;
    const all = await store.getLeads();
    return all.find((l) => l.email.trim().toLowerCase() === norm) ?? null;
  },
  async addLead(lead: Lead): Promise<void> {
    const existing = await store.getLeads();
    const all = [lead, ...existing].slice(0, 1000);
    await getBackend().write(LEADS_FILE, all);
  },
  async updateLead(id: string, patch: Partial<Lead>): Promise<Lead | null> {
    const existing = await store.getLeads();
    const idx = existing.findIndex((l) => l.id === id);
    if (idx === -1) return null;
    existing[idx] = { ...existing[idx], ...patch, id: existing[idx].id, updatedAt: new Date().toISOString() };
    await getBackend().write(LEADS_FILE, existing);
    return existing[idx];
  },

  // Workspace invites (Users & Roles page)
  async getInvites(): Promise<Invite[]> {
    const all = await getBackend().read<Invite[]>(INVITES_FILE, []);
    // Lazy-expire on read so the operator never sees a stale "pending" past
    // its expiry. The store-level write happens on the next mutation.
    const now = Date.now();
    return all.map((inv) =>
      inv.status === "pending" && new Date(inv.expiresAt).getTime() < now
        ? { ...inv, status: "expired" as InviteStatus }
        : inv,
    );
  },
  async getInvite(id: string): Promise<Invite | null> {
    const all = await store.getInvites();
    return all.find((i) => i.id === id) ?? null;
  },
  async getInviteByEmail(email: string): Promise<Invite | null> {
    const norm = email.trim().toLowerCase();
    if (!norm) return null;
    const all = await store.getInvites();
    return all.find((i) => i.email === norm && i.status === "pending") ?? null;
  },
  async getInviteByToken(token: string): Promise<Invite | null> {
    const trimmed = (token ?? "").trim();
    if (!trimmed) return null;
    const all = await store.getInvites();
    return all.find((i) => i.token === trimmed) ?? null;
  },
  async addInvite(invite: Invite): Promise<void> {
    const existing = await getBackend().read<Invite[]>(INVITES_FILE, []);
    const all = [invite, ...existing].slice(0, 500);
    await getBackend().write(INVITES_FILE, all);
  },
  async updateInvite(id: string, patch: Partial<Invite>): Promise<Invite | null> {
    const existing = await getBackend().read<Invite[]>(INVITES_FILE, []);
    const idx = existing.findIndex((i) => i.id === id);
    if (idx === -1) return null;
    existing[idx] = { ...existing[idx], ...patch, id: existing[idx].id };
    await getBackend().write(INVITES_FILE, existing);
    return existing[idx];
  },

  // Programmatic API keys (Bearer auth for /api/v1/*)
  async getApiKeys(): Promise<ApiKey[]> {
    return getBackend().read<ApiKey[]>(API_KEYS_FILE, []);
  },
  async getApiKey(id: string): Promise<ApiKey | null> {
    const all = await store.getApiKeys();
    return all.find((k) => k.id === id) ?? null;
  },
  async getApiKeyByHash(hashedSecret: string): Promise<ApiKey | null> {
    if (!hashedSecret) return null;
    const all = await store.getApiKeys();
    return all.find((k) => k.hashedSecret === hashedSecret) ?? null;
  },
  async addApiKey(key: ApiKey): Promise<void> {
    const existing = await store.getApiKeys();
    // Cap at 100 keys per workspace — operator hits this they're doing
    // something weird and should rotate first.
    const all = [key, ...existing].slice(0, 100);
    await getBackend().write(API_KEYS_FILE, all);
  },
  async updateApiKey(id: string, patch: Partial<ApiKey>): Promise<ApiKey | null> {
    const existing = await store.getApiKeys();
    const idx = existing.findIndex((k) => k.id === id);
    if (idx === -1) return null;
    existing[idx] = { ...existing[idx], ...patch, id: existing[idx].id };
    await getBackend().write(API_KEYS_FILE, existing);
    return existing[idx];
  },
  /**
   * Record one successful API call against the key — bumps lastUsedAt
   * and appends to the rolling 24h usage window. Trims older-than-24h
   * entries on every write to keep the file small.
   */
  async recordApiKeyUse(id: string): Promise<void> {
    const existing = await store.getApiKeys();
    const idx = existing.findIndex((k) => k.id === id);
    if (idx === -1) return;
    const now = Date.now();
    const cutoff = now - 24 * 60 * 60 * 1000;
    const trimmed = (existing[idx].usageWindow ?? []).filter(
      (iso) => new Date(iso).getTime() >= cutoff,
    );
    trimmed.push(new Date(now).toISOString());
    existing[idx] = {
      ...existing[idx],
      usageWindow: trimmed,
      lastUsedAt: new Date(now).toISOString(),
    };
    await getBackend().write(API_KEYS_FILE, existing);
  },

  // ─── Business Directory ────────────────────────────────────────────────
  async getBusinesses(): Promise<BusinessRecord[]> {
    return getBackend().read<BusinessRecord[]>(BUSINESSES_FILE, []);
  },
  async getBusiness(id: string): Promise<BusinessRecord | null> {
    const all = await store.getBusinesses();
    return all.find((b) => b.id === id) ?? null;
  },
  async getBusinessByEmail(email: string): Promise<BusinessRecord | null> {
    const norm = (email ?? "").trim().toLowerCase();
    if (!norm) return null;
    const all = await store.getBusinesses();
    return all.find((b) => (b.email ?? "").trim().toLowerCase() === norm) ?? null;
  },
  /**
   * Lookup by (name + zip) composite — fallback dedup key when an email
   * isn't on the record. Case-insensitive on name; exact match on zip.
   */
  async getBusinessByNameZip(name: string, zip: string): Promise<BusinessRecord | null> {
    const n = (name ?? "").trim().toLowerCase();
    const z = (zip ?? "").trim();
    if (!n || !z) return null;
    const all = await store.getBusinesses();
    return all.find((b) => b.name.trim().toLowerCase() === n && (b.zip ?? "").trim() === z) ?? null;
  },
  async addBusiness(b: BusinessRecord): Promise<void> {
    const existing = await store.getBusinesses();
    // Cap at 100k to keep the file readable. Real ingestion at scale
    // should chunk into multiple files (slice 4+).
    const all = [b, ...existing].slice(0, 100_000);
    await getBackend().write(BUSINESSES_FILE, all);
  },
  async updateBusiness(id: string, patch: Partial<BusinessRecord>): Promise<BusinessRecord | null> {
    const existing = await store.getBusinesses();
    const idx = existing.findIndex((b) => b.id === id);
    if (idx === -1) return null;
    existing[idx] = {
      ...existing[idx],
      ...patch,
      id: existing[idx].id,            // never overwrite id
      createdAt: existing[idx].createdAt, // never overwrite created
      updatedAt: new Date().toISOString(),
    };
    await getBackend().write(BUSINESSES_FILE, existing);
    return existing[idx];
  },
  async deleteBusiness(id: string): Promise<boolean> {
    const existing = await store.getBusinesses();
    const next = existing.filter((b) => b.id !== id);
    if (next.length === existing.length) return false;
    await getBackend().write(BUSINESSES_FILE, next);
    return true;
  },
  /**
   * Bulk upsert from an importer. Dedupe key:
   *   - email if present
   *   - else (name + zip) composite
   *   - else (name + city) composite
   *   - else create new (with a fresh id)
   * Merges incoming non-empty fields into existing records (never
   * overwrites a non-empty value with empty). Returns counts.
   */
  async bulkUpsertBusinesses(rows: Omit<BusinessRecord, "id" | "createdAt" | "updatedAt">[]): Promise<{
    inserted: number;
    updated: number;
    skipped: number;
  }> {
    const existing = await store.getBusinesses();
    let inserted = 0;
    let updated = 0;
    let skipped = 0;
    const now = new Date().toISOString();

    for (const row of rows) {
      if (!row.name || !row.name.trim()) {
        skipped += 1;
        continue;
      }
      // Find dedup match
      let matchIdx = -1;
      const email = (row.email ?? "").trim().toLowerCase();
      if (email) {
        matchIdx = existing.findIndex((b) => (b.email ?? "").trim().toLowerCase() === email);
      }
      if (matchIdx === -1 && row.zip) {
        const n = row.name.trim().toLowerCase();
        const z = row.zip.trim();
        matchIdx = existing.findIndex(
          (b) => b.name.trim().toLowerCase() === n && (b.zip ?? "").trim() === z,
        );
      }
      if (matchIdx === -1 && row.city) {
        const n = row.name.trim().toLowerCase();
        const c = row.city.trim().toLowerCase();
        matchIdx = existing.findIndex(
          (b) => b.name.trim().toLowerCase() === n && (b.city ?? "").trim().toLowerCase() === c,
        );
      }

      if (matchIdx === -1) {
        existing.unshift({
          ...row,
          id: `biz_${Math.random().toString(36).slice(2, 10)}${Date.now().toString(36).slice(-4)}`,
          createdAt: now,
          updatedAt: now,
        });
        inserted += 1;
      } else {
        // Merge: only fill missing fields, never overwrite non-empty existing values
        const cur = existing[matchIdx];
        const merged: BusinessRecord = { ...cur };
        for (const k of Object.keys(row) as (keyof typeof row)[]) {
          const incoming = row[k];
          if (incoming === undefined || incoming === null || incoming === "") continue;
          const curVal = (cur as Record<string, unknown>)[k as string];
          if (curVal === undefined || curVal === null || curVal === "") {
            (merged as Record<string, unknown>)[k as string] = incoming;
          }
        }
        merged.updatedAt = now;
        existing[matchIdx] = merged;
        updated += 1;
      }
    }

    await getBackend().write(BUSINESSES_FILE, existing.slice(0, 100_000));
    return { inserted, updated, skipped };
  },

  // ─── Supply Edges (Commercial Intelligence Graph) ──────────────────────
  async getSupplyEdges(): Promise<SupplyEdge[]> {
    return getBackend().read<SupplyEdge[]>(SUPPLY_EDGES_FILE, []);
  },
  async getSupplyEdgesFromBusiness(businessId: string): Promise<SupplyEdge[]> {
    const all = await store.getSupplyEdges();
    return all.filter((e) => e.fromBusinessId === businessId);
  },
  async getSupplyEdgesByBrand(brandName: string): Promise<SupplyEdge[]> {
    const norm = brandName.trim().toLowerCase();
    if (!norm) return [];
    const all = await store.getSupplyEdges();
    return all.filter((e) => e.toName.trim().toLowerCase() === norm);
  },
  /**
   * Idempotent upsert keyed on (fromBusinessId, toName, kind). Re-observing
   * the same edge bumps lastSeenAt + raises confidence to the higher of
   * the existing and incoming values. Source is preserved on the FIRST
   * observation — transaction-observed edges (higher signal) stay tagged
   * "transaction" even if a later ai_profile scan re-confirms.
   */
  async upsertSupplyEdge(
    edge: Omit<SupplyEdge, "id" | "observedAt" | "lastSeenAt"> & { observedAt?: string },
  ): Promise<SupplyEdge> {
    const existing = await store.getSupplyEdges();
    const now = new Date().toISOString();
    const key = supplyEdgeDedupKey(edge);
    const idx = existing.findIndex(
      (e) => supplyEdgeDedupKey(e) === key,
    );
    if (idx === -1) {
      const created: SupplyEdge = {
        id: `edge_${Math.random().toString(36).slice(2, 10)}${Date.now().toString(36).slice(-4)}`,
        fromBusinessId: edge.fromBusinessId,
        fromBusinessName: edge.fromBusinessName,
        toName: edge.toName.trim(),
        toBusinessId: edge.toBusinessId,
        kind: edge.kind,
        source: edge.source,
        confidence: Math.max(0, Math.min(100, Math.round(edge.confidence))),
        evidence: edge.evidence,
        observedAt: edge.observedAt ?? now,
        lastSeenAt: now,
        alternativesFound: edge.alternativesFound,
      };
      // Cap at 500k edges to keep the file manageable. Drop oldest by
      // lastSeenAt when capped (LRU-ish).
      const all = [...existing, created].sort(
        (a, b) => new Date(b.lastSeenAt).getTime() - new Date(a.lastSeenAt).getTime(),
      ).slice(0, 500_000);
      await getBackend().write(SUPPLY_EDGES_FILE, all);
      return created;
    }
    const cur = existing[idx];
    const merged: SupplyEdge = {
      ...cur,
      // Preserve original source attribution unless transaction edges
      // upgrade an ai_profile edge — those replace.
      source: cur.source === "transaction" ? cur.source : edge.source,
      confidence: Math.max(cur.confidence, Math.round(edge.confidence)),
      evidence: edge.evidence ?? cur.evidence,
      lastSeenAt: now,
      // Take higher of the two on alternativesFound
      alternativesFound: Math.max(cur.alternativesFound ?? 0, edge.alternativesFound ?? 0) || undefined,
      // Latest toBusinessId wins (we may not have known the id at first observation)
      toBusinessId: edge.toBusinessId ?? cur.toBusinessId,
    };
    existing[idx] = merged;
    await getBackend().write(SUPPLY_EDGES_FILE, existing);
    return merged;
  },
  async deleteSupplyEdge(id: string): Promise<boolean> {
    const existing = await store.getSupplyEdges();
    const next = existing.filter((e) => e.id !== id);
    if (next.length === existing.length) return false;
    await getBackend().write(SUPPLY_EDGES_FILE, next);
    return true;
  },
  /**
   * Remove every edge originating from a business — used when an
   * operator deletes the business OR re-scans and wants to start fresh.
   * Doesn't touch inbound edges (edges where this business is the `to`).
   */
  async deleteSupplyEdgesFromBusiness(businessId: string): Promise<number> {
    const existing = await store.getSupplyEdges();
    const next = existing.filter((e) => e.fromBusinessId !== businessId);
    const removed = existing.length - next.length;
    if (removed > 0) await getBackend().write(SUPPLY_EDGES_FILE, next);
    return removed;
  },

  // Pipeline runs (snapshots for /share/[id])
  async getPipelineRuns(): Promise<StoredPipelineRun[]> {
    return getBackend().read<StoredPipelineRun[]>(PIPELINE_RUNS_FILE, []);
  },
  async getPipelineRun(id: string): Promise<StoredPipelineRun | null> {
    const runs = await store.getPipelineRuns();
    return runs.find((r) => r.id === id) ?? null;
  },
  async savePipelineRun(run: StoredPipelineRun): Promise<void> {
    const existing = await store.getPipelineRuns();
    const all = [run, ...existing].slice(0, 50);
    await getBackend().write(PIPELINE_RUNS_FILE, all);
  },
  async appendShareAccess(id: string, entry: ShareAccessEntry): Promise<StoredPipelineRun | null> {
    const runs = await store.getPipelineRuns();
    const idx = runs.findIndex((r) => r.id === id);
    if (idx === -1) return null;
    const log = runs[idx].accessLog ?? [];
    runs[idx].accessLog = [entry, ...log].slice(0, 50);
    await getBackend().write(PIPELINE_RUNS_FILE, runs);
    return runs[idx];
  },
  async revokeShareToken(id: string): Promise<StoredPipelineRun | null> {
    const runs = await store.getPipelineRuns();
    const idx = runs.findIndex((r) => r.id === id);
    if (idx === -1) return null;
    if (runs[idx].revoked) return runs[idx];
    runs[idx].revoked = true;
    runs[idx].revokedAt = new Date().toISOString();
    await getBackend().write(PIPELINE_RUNS_FILE, runs);
    return runs[idx];
  },
  async addShareLink(
    id: string,
    link: ShareLink,
  ): Promise<{ run: StoredPipelineRun; link: ShareLink } | null> {
    const runs = await store.getPipelineRuns();
    const idx = runs.findIndex((r) => r.id === id);
    if (idx === -1) return null;
    const links = runs[idx].shareLinks ?? [];
    runs[idx].shareLinks = [link, ...links].slice(0, 25);
    await getBackend().write(PIPELINE_RUNS_FILE, runs);
    return { run: runs[idx], link };
  },
  async revokeShareLink(id: string, token: string): Promise<StoredPipelineRun | null> {
    const runs = await store.getPipelineRuns();
    const idx = runs.findIndex((r) => r.id === id);
    if (idx === -1) return null;
    const links = runs[idx].shareLinks ?? [];
    const linkIdx = links.findIndex((l) => l.token === token);
    if (linkIdx === -1) return null;
    if (links[linkIdx].revoked) return runs[idx];
    links[linkIdx].revoked = true;
    links[linkIdx].revokedAt = new Date().toISOString();
    runs[idx].shareLinks = links;
    await getBackend().write(PIPELINE_RUNS_FILE, runs);
    return runs[idx];
  },
  /**
   * Pure function — synchronous on purpose. Resolves a presented token
   * against the legacy default OR a named link in the GIVEN run snapshot.
   * No I/O, callable from anywhere.
   */
  resolveShareToken(
    run: StoredPipelineRun,
    token: string,
  ):
    | {
        kind: "default";
        expiresAt?: string;
        revoked: boolean;
        revokedAt?: string;
        label: string;
        scope: ShareScope;
      }
    | { kind: "named"; link: ShareLink; scope: ShareScope }
    | null {
    if (!token) return null;
    if (token === run.shareToken) {
      return {
        kind: "default",
        expiresAt: run.shareExpiresAt,
        revoked: run.revoked === true,
        revokedAt: run.revokedAt,
        label: "Default link",
        scope: "full",
      };
    }
    const named = run.shareLinks?.find((l) => l.token === token);
    if (named) {
      const scope: ShareScope = named.scope ?? "recipient";
      return { kind: "named", link: named, scope };
    }
    return null;
  },

  // Drafts
  async getDrafts(): Promise<OutreachDraft[]> {
    return getBackend().read<OutreachDraft[]>(DRAFTS_FILE, []);
  },
  async saveDraft(draft: OutreachDraft): Promise<void> {
    const existing = await store.getDrafts();
    const all = [draft, ...existing].slice(0, 200);
    await getBackend().write(DRAFTS_FILE, all);
  },
  async updateDraftStatus(id: string, status: OutreachDraft["status"]): Promise<OutreachDraft | null> {
    const drafts = await store.getDrafts();
    const idx = drafts.findIndex((d) => d.id === id);
    if (idx === -1) return null;
    drafts[idx].status = status;
    await getBackend().write(DRAFTS_FILE, drafts);
    return drafts[idx];
  },
  async patchDraft(id: string, patch: Partial<OutreachDraft>): Promise<OutreachDraft | null> {
    const drafts = await store.getDrafts();
    const idx = drafts.findIndex((d) => d.id === id);
    if (idx === -1) return null;
    drafts[idx] = { ...drafts[idx], ...patch };
    await getBackend().write(DRAFTS_FILE, drafts);
    return drafts[idx];
  },
  async attachPipelineToDraft(draftId: string, pipelineId: string): Promise<OutreachDraft | null> {
    const drafts = await store.getDrafts();
    const idx = drafts.findIndex((d) => d.id === draftId);
    if (idx === -1) return null;
    if (drafts[idx].pipelineId === pipelineId) return drafts[idx];
    drafts[idx].pipelineId = pipelineId;
    await getBackend().write(DRAFTS_FILE, drafts);
    return drafts[idx];
  },
  async appendToThread(id: string, message: ThreadMessage): Promise<OutreachDraft | null> {
    const drafts = await store.getDrafts();
    const idx = drafts.findIndex((d) => d.id === id);
    if (idx === -1) return null;
    const current = drafts[idx].thread ?? [];
    drafts[idx].thread = [...current, message];
    await getBackend().write(DRAFTS_FILE, drafts);
    return drafts[idx];
  },
  async getDraft(id: string): Promise<OutreachDraft | null> {
    const drafts = await store.getDrafts();
    return drafts.find((d) => d.id === id) ?? null;
  },
  async getDraftByReplyToken(token: string): Promise<OutreachDraft | null> {
    const trimmed = (token ?? "").trim();
    if (!trimmed || trimmed.length < 16) return null;
    const drafts = await store.getDrafts();
    return drafts.find((d) => d.replyToken === trimmed) ?? null;
  },

  // Quotes
  async getQuotes(): Promise<Quote[]> {
    return getBackend().read<Quote[]>(QUOTES_FILE, []);
  },
  async getQuote(id: string): Promise<Quote | null> {
    const quotes = await store.getQuotes();
    return quotes.find((q) => q.id === id) ?? null;
  },
  async saveQuote(quote: Quote): Promise<void> {
    const existing = await store.getQuotes();
    const all = [quote, ...existing].slice(0, 200);
    await getBackend().write(QUOTES_FILE, all);
  },
  async patchQuote(id: string, patch: Partial<Quote>): Promise<Quote | null> {
    const quotes = await store.getQuotes();
    const idx = quotes.findIndex((q) => q.id === id);
    if (idx === -1) return null;
    quotes[idx] = { ...quotes[idx], ...patch };
    await getBackend().write(QUOTES_FILE, quotes);
    return quotes[idx];
  },

  // ─── Spend ledger (production: daily-budget circuit breaker) ────────────
  async getSpendLedger(): Promise<SpendLedgerEntry[]> {
    return getBackend().read<SpendLedgerEntry[]>(SPEND_LEDGER_FILE, []);
  },
  /**
   * Atomic-ish bump: read, increment, write. NOT thread-safe across lambdas
   * (file backend) — KV backend gets it close. For higher-volume usage with
   * KV, swap to INCRBY + HINCRBY.
   */
  async addSpend(args: { agent: string; cost: number }): Promise<void> {
    const date = new Date().toISOString().slice(0, 10);
    const ledger = await store.getSpendLedger();
    let entry = ledger.find((e) => e.date === date);
    if (!entry) {
      entry = { date, callCount: 0, totalCostUsd: 0, byAgent: {} };
      ledger.unshift(entry);
    }
    entry.callCount += 1;
    entry.totalCostUsd += args.cost;
    const a = entry.byAgent[args.agent] ?? { calls: 0, cost: 0 };
    a.calls += 1;
    a.cost += args.cost;
    entry.byAgent[args.agent] = a;
    // Cap at 90 days of history
    const trimmed = ledger.slice(0, 90);
    await getBackend().write(SPEND_LEDGER_FILE, trimmed);
  },
  async getTodaySpend(): Promise<{ cost: number; calls: number }> {
    const date = new Date().toISOString().slice(0, 10);
    const ledger = await store.getSpendLedger();
    const entry = ledger.find((e) => e.date === date);
    if (!entry) return { cost: 0, calls: 0 };
    return { cost: entry.totalCostUsd, calls: entry.callCount };
  },

  // ─── Transactions (slice 39) ───────────────────────────────────────────
  async getTransactions(): Promise<Transaction[]> {
    return getBackend().read<Transaction[]>(TRANSACTIONS_FILE, []);
  },
  async getTransaction(id: string): Promise<Transaction | null> {
    const txns = await store.getTransactions();
    return txns.find((t) => t.id === id) ?? null;
  },
  async getTransactionByQuote(quoteId: string): Promise<Transaction | null> {
    const txns = await store.getTransactions();
    return txns.find((t) => t.quoteId === quoteId) ?? null;
  },
  async saveTransaction(t: Transaction): Promise<void> {
    const existing = await store.getTransactions();
    const all = [t, ...existing.filter((x) => x.id !== t.id)].slice(0, 500);
    await getBackend().write(TRANSACTIONS_FILE, all);
  },
  async patchTransaction(id: string, patch: Partial<Transaction>): Promise<Transaction | null> {
    const txns = await store.getTransactions();
    const idx = txns.findIndex((t) => t.id === id);
    if (idx === -1) return null;
    txns[idx] = { ...txns[idx], ...patch, updatedAt: new Date().toISOString() };
    await getBackend().write(TRANSACTIONS_FILE, txns);
    return txns[idx];
  },
  async appendTransactionEvent(
    id: string,
    event: TransactionEvent,
  ): Promise<Transaction | null> {
    const txns = await store.getTransactions();
    const idx = txns.findIndex((t) => t.id === id);
    if (idx === -1) return null;
    txns[idx].stateHistory = [...(txns[idx].stateHistory ?? []), event];
    txns[idx].state = event.state;
    txns[idx].updatedAt = event.ts;
    await getBackend().write(TRANSACTIONS_FILE, txns);
    return txns[idx];
  },

  // ─── Revenue ledger (slice 39) ─────────────────────────────────────────
  async getRevenueLedger(): Promise<RevenueEntry[]> {
    return getBackend().read<RevenueEntry[]>(REVENUE_LEDGER_FILE, []);
  },
  async addRevenueEntry(entry: RevenueEntry): Promise<void> {
    const existing = await store.getRevenueLedger();
    const all = [entry, ...existing].slice(0, 5000);
    await getBackend().write(REVENUE_LEDGER_FILE, all);
  },

  // ─── GDPR / forget-buyer ───────────────────────────────────────────────
  /**
   * Purge all data tied to a buyer email. Returns counts of what was removed.
   * Does NOT touch pipeline-runs (they store anonymized summaries — buyer
   * email is never persisted there).
   */
  async forgetBuyer(email: string): Promise<{
    drafts: number;
    threadMessages: number;
    discoveredBuyers: number;
    accessLogEntries: number;
  }> {
    const target = email.trim().toLowerCase();
    if (!target) {
      return { drafts: 0, threadMessages: 0, discoveredBuyers: 0, accessLogEntries: 0 };
    }
    let drafts = 0;
    let threadMessages = 0;
    let discoveredBuyers = 0;
    let accessLogEntries = 0;

    // 1. Purge drafts that match (by sentToEmail OR redirectedFromEmail)
    const allDrafts = await store.getDrafts();
    const keepDrafts: OutreachDraft[] = [];
    const removedDraftIds = new Set<string>();
    for (const d of allDrafts) {
      const sentTo = (d.sentToEmail ?? "").toLowerCase();
      const redirectedFrom = (d.redirectedFromEmail ?? "").toLowerCase();
      if (sentTo === target || redirectedFrom === target) {
        drafts += 1;
        threadMessages += (d.thread ?? []).length;
        removedDraftIds.add(d.id);
      } else {
        keepDrafts.push(d);
      }
    }
    if (keepDrafts.length !== allDrafts.length) {
      await getBackend().write(DRAFTS_FILE, keepDrafts);
    }

    // 2. Purge discovered buyers with that email
    const buyers = await store.getDiscoveredBuyers();
    const keepBuyers = buyers.filter((b) => {
      const e = (b.email ?? "").toLowerCase();
      if (e === target) {
        discoveredBuyers += 1;
        return false;
      }
      return true;
    });
    if (keepBuyers.length !== buyers.length) {
      await getBackend().write(BUYERS_FILE, keepBuyers);
    }

    // 3. Drop access-log entries with the buyer's IP would over-purge
    //    (IPs aren't email-bound). Instead, drop access entries tied to a
    //    revoked/removed draft's shareLinkToken.
    const removedTokens = new Set<string>();
    for (const d of allDrafts) {
      if (!removedDraftIds.has(d.id)) continue;
      if (d.shareLinkToken) removedTokens.add(d.shareLinkToken);
      if (d.smsShareLinkToken) removedTokens.add(d.smsShareLinkToken);
      if (d.linkedinShareLinkToken) removedTokens.add(d.linkedinShareLinkToken);
    }
    if (removedTokens.size > 0) {
      const runs = await store.getPipelineRuns();
      let touched = false;
      for (const run of runs) {
        const log = run.accessLog ?? [];
        const filtered = log.filter((e) => {
          if (e.linkToken && removedTokens.has(e.linkToken)) {
            accessLogEntries += 1;
            return false;
          }
          return true;
        });
        if (filtered.length !== log.length) {
          run.accessLog = filtered;
          touched = true;
        }
        // Also revoke the named links so any cached reference returns 410
        if (run.shareLinks) {
          for (const link of run.shareLinks) {
            if (removedTokens.has(link.token) && !link.revoked) {
              link.revoked = true;
              link.revokedAt = new Date().toISOString();
              touched = true;
            }
          }
        }
      }
      if (touched) {
        await getBackend().write(PIPELINE_RUNS_FILE, runs);
      }
    }

    return { drafts, threadMessages, discoveredBuyers, accessLogEntries };
  },
};
